services:
  - type: web
    name: admission-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 